import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HamburgerMenu from "@/components/HamburgerMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Stats {
  failStats: Record<number, number>;
  mostFailedNumber?: number;
  timePlayed?: number;
}

function trackFail(number: number): void {
  const stats: Stats = JSON.parse(localStorage.getItem("stats") || "{}");
  stats.failStats = stats.failStats || {};
  stats.failStats[number] = (stats.failStats[number] || 0) + 1;
  stats.mostFailedNumber = Number(Object.keys(stats.failStats).reduce((a, b) =>
    stats.failStats[Number(a)] > stats.failStats[Number(b)] ? a : b
  ));
  localStorage.setItem("stats", JSON.stringify(stats));
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <header className="absolute top-4 left-4">
          <HamburgerMenu />
        </header>
        {children}
      </body>
    </html>
  );
}
